receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 20

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:30001"
    namespace: otelcol_gateway
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: false
    add_metric_suffixes: true
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  zpages:

service:
  telemetry:
    metrics:
      address: ":8888"
  extensions: [zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
